<?php
// admin/backup-database.php - Backup database via PHP murni
// VERSI: 3.0 - CSRF protection + audit log + error handling

require_once __DIR__ . '/../includes/functions.php';
requireLogin();

// Hanya superadmin yang boleh backup
if (!isset($_SESSION['admin_role']) || $_SESSION['admin_role'] !== 'superadmin') {
    die('Akses ditolak. Hanya superadmin yang dapat melakukan backup.');
}

// ============================================
// CSRF VALIDATION (via GET)
// ============================================
$tokenGet = $_GET['csrf_token'] ?? '';
$tokenSes = $_SESSION['csrf_token'] ?? '';
if (empty($tokenGet) || empty($tokenSes) || !hash_equals($tokenSes, $tokenGet)) {
    // Token tidak valid — redirect ke halaman pengaturan dengan pesan error
    redirect('admin/pengaturan.php', 'Request backup tidak valid.', 'error');
    exit();
}

// ============================================
// FUNGSI BACKUP PURE PHP
// ============================================

/**
 * Generate SQL backup dari semua tabel.
 *
 * @return string SQL dump
 * @throws Exception jika gagal membaca tabel atau menulis data
 */
function backupDatabase(): string {
    $conn = getConnection();
    $driver = DB_CONNECTION;

    $output  = "-- ============================================\n";
    $output .= "-- Backup Database: " . DB_NAME . " (" . strtoupper($driver) . ")\n";
    $output .= "-- Tanggal: " . date('Y-m-d H:i:s') . " WIB\n";
    $output .= "-- Host: " . DB_HOST . "\n";
    $output .= "-- Generated by: " . ($_SESSION['admin_name'] ?? 'Admin') . "\n";
    $output .= "-- ============================================\n\n";

    if ($driver !== 'pgsql') {
        $output .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
        $output .= "SET AUTOCOMMIT = 0;\n";
        $output .= "START TRANSACTION;\n";
        $output .= "SET time_zone = \"+07:00\";\n\n";
    }

    // Ambil semua nama tabel
    $tables = [];
    try {
        if ($driver === 'pgsql') {
            $stmt = $conn->query("SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname = 'public'");
        } else {
            $stmt = $conn->query("SHOW TABLES");
        }
        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $tables[] = $row[0];
        }
    } catch (PDOException $e) {
        throw new Exception("Gagal mengambil daftar tabel: " . $e->getMessage());
    }

    foreach ($tables as $table) {
        $quotedTable = ($driver === 'pgsql') ? "\"$table\"" : "`$table`";

        $output .= "-- ----------------------------------------\n";
        $output .= "-- Struktur tabel $quotedTable\n";
        $output .= "-- ----------------------------------------\n\n";
        
        if ($driver === 'pgsql') {
            $output .= "DROP TABLE IF EXISTS $quotedTable CASCADE;\n";
            // Untuk PostgreSQL, kita buat skema sederhana via information_schema
            $colsStmt = $conn->prepare("SELECT column_name, data_type, is_nullable, column_default 
                                       FROM information_schema.columns 
                                       WHERE table_name = ? AND table_schema = 'public'
                                       ORDER BY ordinal_position");
            $colsStmt->execute([$table]);
            $cols = $colsStmt->fetchAll(PDO::FETCH_ASSOC);
            
            $output .= "CREATE TABLE $quotedTable (\n";
            $colDefs = [];
            foreach ($cols as $c) {
                $def = "    \"" . $c['column_name'] . "\" " . $c['data_type'];
                if ($c['is_nullable'] === 'NO') $def .= " NOT NULL";
                if ($c['column_default']) $def .= " DEFAULT " . $c['column_default'];
                $colDefs[] = $def;
            }
            $output .= implode(",\n", $colDefs) . "\n);\n\n";
        } else {
            $output .= "DROP TABLE IF EXISTS $quotedTable;\n";
            $createStmt = $conn->query("SHOW CREATE TABLE $quotedTable");
            $createRow = $createStmt->fetch(PDO::FETCH_NUM);
            $output .= $createRow[1] . ";\n\n";
        }

        // ----------------------------------
        // DATA TABEL
        // ----------------------------------
        $dataStmt = $conn->query("SELECT * FROM $quotedTable");
        $rows = $dataStmt->fetchAll(PDO::FETCH_ASSOC);

        if (empty($rows)) {
            $output .= "-- (Tidak ada data di tabel $quotedTable)\n\n";
            continue;
        }

        $output .= "-- Data untuk tabel $quotedTable\n";
        foreach ($rows as $row) {
            $cols = [];
            $vals = [];
            foreach ($row as $col => $val) {
                $cols[] = ($driver === 'pgsql') ? "\"$col\"" : "`$col`";
                if ($val === null) {
                    $vals[] = "NULL";
                } else {
                    $vals[] = $conn->quote($val);
                }
            }
            $output .= "INSERT INTO $quotedTable (" . implode(', ', $cols) . ") VALUES (" . implode(', ', $vals) . ");\n";
        }
        $output .= "\n";
    }

    if ($driver !== 'pgsql') {
        $output .= "COMMIT;\n";
    }
    return $output;
}

// ============================================
// GENERATE & KIRIM FILE BACKUP
// ============================================

try {
    $sqlContent = backupDatabase();
    $filename   = 'backup-' . DB_NAME . '-' . date('Y-m-d-H-i-s') . '.sql';

    // Audit log: catat backup
    $sizeMB = round(strlen($sqlContent) / 1024 / 1024, 2);
    auditLog('BACKUP', 'database', null, "Backup database berhasil (ukuran: {$sizeMB} MB)");

    // Bersihkan buffer sebelum mengirim header
    if (ob_get_level()) ob_end_clean();

    // Pastikan header belum terkirim
    if (headers_sent()) {
        throw new Exception('Header sudah terkirim, tidak bisa mengirim file.');
    }

    // Kirim file
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . strlen($sqlContent));
    header('Pragma: no-cache');
    header('Expires: 0');

    echo $sqlContent;
    exit;

} catch (Exception $e) {
    error_log("[BACKUP ERROR] " . $e->getMessage());
    // Tampilkan pesan error yang aman (tidak bocorkan detail internal)
    if (APP_ENV === 'development') {
        die("Gagal membuat backup: " . htmlspecialchars($e->getMessage(), ENT_QUOTES, 'UTF-8'));
    } else {
        die("Gagal membuat backup. Silakan coba lagi atau hubungi administrator.");
    }
}