<?php
// admin/backup-database.php - Backup database via PHP murni
// VERSI: 3.0 - CSRF protection + audit log + error handling

require_once __DIR__ . '/../includes/functions.php';
requireLogin();

// Hanya superadmin yang boleh backup
if (!isset($_SESSION['admin_role']) || $_SESSION['admin_role'] !== 'superadmin') {
    die('Akses ditolak. Hanya superadmin yang dapat melakukan backup.');
}

// ============================================
// CSRF VALIDATION (via GET)
// ============================================
$tokenGet = $_GET['csrf_token'] ?? '';
$tokenSes = $_SESSION['csrf_token'] ?? '';
if (empty($tokenGet) || empty($tokenSes) || !hash_equals($tokenSes, $tokenGet)) {
    // Token tidak valid — redirect ke halaman pengaturan dengan pesan error
    redirect('admin/pengaturan.php', 'Request backup tidak valid.', 'error');
    exit();
}

// ============================================
// FUNGSI BACKUP PURE PHP
// ============================================

/**
 * Generate SQL backup dari semua tabel.
 *
 * @return string SQL dump
 * @throws Exception jika gagal membaca tabel atau menulis data
 */
function backupDatabase(): string {
    $conn = getConnection();

    $output  = "-- ============================================\n";
    $output .= "-- Backup Database: " . DB_NAME . "\n";
    $output .= "-- Tanggal: " . date('Y-m-d H:i:s') . " WIB\n";
    $output .= "-- Host: " . DB_HOST . "\n";
    $output .= "-- Generated by: " . ($_SESSION['admin_name'] ?? 'Admin') . "\n";
    $output .= "-- ============================================\n\n";
    $output .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
    $output .= "SET AUTOCOMMIT = 0;\n";
    $output .= "START TRANSACTION;\n";
    $output .= "SET time_zone = \"+07:00\";\n\n";

    // Ambil semua nama tabel
    $tables = [];
    $result = $conn->query("SHOW TABLES");
    if (!$result) {
        throw new Exception("Gagal mengambil daftar tabel: " . $conn->error);
    }
    while ($row = $result->fetch_row()) {
        $tables[] = $row[0];
    }

    foreach ($tables as $table) {
        // ----------------------------------
        // STRUKTUR TABEL
        // ----------------------------------
        $output .= "-- ----------------------------------------\n";
        $output .= "-- Struktur tabel `$table`\n";
        $output .= "-- ----------------------------------------\n\n";
        $output .= "DROP TABLE IF EXISTS `$table`;\n";

        $createResult = $conn->query("SHOW CREATE TABLE `$table`");
        if (!$createResult) {
            throw new Exception("Gagal membaca struktur tabel `$table`: " . $conn->error);
        }

        $createRow = $createResult->fetch_row();
        $output .= $createRow[1] . ";\n\n";

        // ----------------------------------
        // DATA TABEL
        // ----------------------------------
        $dataResult = $conn->query("SELECT * FROM `$table`");
        if (!$dataResult) {
            throw new Exception("Gagal membaca data tabel `$table`: " . $conn->error);
        }

        if ($dataResult->num_rows === 0) {
            $output .= "-- (Tidak ada data di tabel `$table`)\n\n";
            continue;
        }

        $output .= "-- Data untuk tabel `$table`\n";

        // Ambil nama kolom
        $fields      = $dataResult->fetch_fields();
        $columnNames = array_map(fn($f) => "`{$f->name}`", $fields);
        $columnList  = implode(', ', $columnNames);

        // Tulis INSERT per baris
        while ($row = $dataResult->fetch_assoc()) {
            $values = [];
            foreach ($row as $value) {
                if ($value === null) {
                    $values[] = 'NULL';
                } else {
                    $values[] = "'" . $conn->real_escape_string($value) . "'";
                }
            }
            $output .= "INSERT INTO `$table` ($columnList) VALUES (" . implode(', ', $values) . ");\n";
        }

        $output .= "\n";
    }

    $output .= "COMMIT;\n";
    return $output;
}

// ============================================
// GENERATE & KIRIM FILE BACKUP
// ============================================

try {
    $sqlContent = backupDatabase();
    $filename   = 'backup-' . DB_NAME . '-' . date('Y-m-d-H-i-s') . '.sql';

    // Audit log: catat backup
    $sizeMB = round(strlen($sqlContent) / 1024 / 1024, 2);
    auditLog('BACKUP', 'database', null, "Backup database berhasil (ukuran: {$sizeMB} MB)");

    // Bersihkan buffer sebelum mengirim header
    if (ob_get_level()) ob_end_clean();

    // Pastikan header belum terkirim
    if (headers_sent()) {
        throw new Exception('Header sudah terkirim, tidak bisa mengirim file.');
    }

    // Kirim file
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . strlen($sqlContent));
    header('Pragma: no-cache');
    header('Expires: 0');

    echo $sqlContent;
    exit;

} catch (Exception $e) {
    error_log("[BACKUP ERROR] " . $e->getMessage());
    // Tampilkan pesan error yang aman (tidak bocorkan detail internal)
    if (APP_ENV === 'development') {
        die("Gagal membuat backup: " . htmlspecialchars($e->getMessage(), ENT_QUOTES, 'UTF-8'));
    } else {
        die("Gagal membuat backup. Silakan coba lagi atau hubungi administrator.");
    }
}